repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            args: [--safe, --quiet]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: trailing-whitespace
          - id: fix-encoding-pragma
            args: [--remove]
          - id: check-yaml
          - id: debug-statements
            exclude: _pytest/(debugging|hookspec).py
            language_version: python3
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
          - id: isort
            files: ^(cotton2k/|tests/|setup.py)
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: v3.0.0a4
      hooks:
          - id: pylint
            additional_dependencies: [appdirs, numpy>=1.21, pint, pyenchant>=3.1.1, scipy, "sqlalchemy[mypy]"]
            files: ^cotton2k/
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.942
      hooks:
          - id: mypy
            additional_dependencies: [appdirs-stubs, numpy>=1.21, pint, scipy, "sqlalchemy[mypy]"]
            files: ^cotton2k/
            args: [--show-error-codes]
