import datetime

class Climate:
    def __init__(self, climate_start_date, climate): ...
    def __getitem__(self, item): ...

class FruitingBranch: ...

class Simulation:
    climate: list
    start_date: datetime.date
    version: int
    year: int
    def __init__(self, version: int = 0x0400, **kwargs): ...

class SoilImpedance:
    @property
    def curves(self): ...
    @curves.setter
    def curves(self, impedance_table): ...

class Soil: ...

class SoilInit:
    lyrsol: int
    def __init__(self, initial, hydrology): ...

class State: ...
class VegetativeBranch: ...
